CREATE TABLE `friends` (
	`player_id` VARCHAR(255) NULL DEFAULT NULL,
	`friend_ids` VARCHAR(255) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `players` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL DEFAULT '0',
	`uuid` VARCHAR(50) NOT NULL DEFAULT '0',
	`ip` VARCHAR(50) NOT NULL DEFAULT '0',
	`first_join` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	INDEX `Schlüssel 1` (`id`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=3
;

CREATE TABLE `request` (
	`from_id` VARCHAR(255) NOT NULL,
	`to_id` VARCHAR(255) NOT NULL,
	`status` TINYINT(4) NOT NULL DEFAULT '0',
	`time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
